services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    image: comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    gpus: all
    environment:
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib64/stubs
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./models:/app/ComfyUI/models
      - ./custom_nodes:/app/ComfyUI/custom_nodes
      - ./output:/app/ComfyUI/output
      - ./input:/app/ComfyUI/input
      - comfyui_venv:/venv
      - ./extensions.conf:/app/extensions.conf:ro
      - ./models.conf:/app/models.conf:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  comfyui_venv:
    name: comfyui_venv
    driver: local
